### ISSUE TITLE
Crash during user file list search

### ISSUE THREAD

**Issue by Plexuser50** [airdcpp/airdcpp-windows#131] opened 2024-08-22 15:49 UTC
### Prerequisites

- [X] This is not a [support issue or a question](https://github.com/airdcpp/airdcpp-windows/discussions)
- [X] I performed a [cursory search of the issue tracker](https://github.com/airdcpp/airdcpp-windows/issues) to avoid opening a duplicate issue
- [X] I am running the latest version of AirDC++

### Describe the issue

When browsing a user's file list, I selected a director on the left hand side, chose 'Find', entered my search term, once the first directory was returned that contained a match for what was being search, I used the filter to only highlight folders in the directory that matched what I was searching for. Once I was finished browsing that directory to see all the matches from my filtered search, I the 'Next' button beside 'Find' and that's when the crash happens.

### Expected behavior

After hitting the 'Next' button, I was expecting the search to continue by finding the next directory that contained a folder name that matched what I was searching for.

### Actual behavior

Instead, the program (AirDC++ 4.21 x64)

### Steps to reproduce the behavior if needed

1. Right click on a user and select "Browse file list".
2. Click on 'Find' and enter a search term and start search.
3. When the search term is found in a directory, enter the same search term in the 'Filter' section to eliminate all other folders in the directory.
4. Hit 'Next' to find the next directory that contains your search term.
5. Crash happens.

### Crash log

```shell
Code: c0000005 ( Access violation )
Version: AirDC++ 4.21 x64
Build: 4688
Major: 6
Minor: 2
Build: 9200
SP: 0
Type: 1
Time: 2024-08-22 11:33:50
TTH: XVD7Y4Y3ZK7WZVKBIITFBKENJZ4XJD7NOWVPHVY

C:\Projects\airdc-git\windows\DirectoryListingFrm.cpp(1106): DirectoryListingFrame::insertItems
C:\Projects\airdc-git\windows\DirectoryListingFrm.cpp(1091): DirectoryListingFrame::filterList
C:\Projects\airdc-git\windows\DirectoryListingFrm.h(120): DirectoryListingFrame::ProcessWindowMessage
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\atlmfc\include\atlwin.h(3576): ATL::CWindowImplBaseT<WTL::CMDIWindow=0x2F5C1F88,ATL::CWinTraits<1456406528=0x00007FFA,64> >::WindowProc
atlthunk!0x7FFA2F5C1F88: ?
USER32!0x7FFA5752EF5C: CallWindowProcW
USER32!0x7FFA5752E684: DispatchMessageW
C:\Projects\airdc-git\windows\WTL\atlapp.h(666): WTL::CMessageLoop::Run
C:\Projects\airdc-git\windows\WinClient.cpp(456): WinClient::run
C:\Projects\airdc-git\windows\main.cpp(337): wWinMain
D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288): __scrt_common_main_seh
KERNEL32!0x7FFA576E7374: BaseThreadInitThunk
ntdll!0x7FFA5803CC91: RtlUserThreadStart
```

### AirDC++ version and architecture (x86 or x64)

4.21 x64

### Operating System name, version and architecture

Windows 10 Pro x64

**Comment by maksis** [comment] 2024-09-23 19:07
Could you see whether you can still reproduce this issue with the latest beta? There are various filelist-related fixes and I can't make it crash.

**Comment by Plexuser50** [comment] 2024-09-25 00:08
> Could you see whether you can still reproduce this issue with the latest beta? There are various filelist-related fixes and I can't make it crash.

I was still able to reproduce the crash by following the same steps I described in my post.
![dc++_crash](https://github.com/user-attachments/assets/2520a1cd-98d1-4605-9ccc-c443162ca5a6)

**Comment by maksis** [comment] 2024-10-13 14:54
Can anyone else reproduce this?

**Comment by infectormp** [comment] 2024-10-13 17:33
nope

**Comment by maksis** [comment] 2024-10-13 17:36
@Plexuser50 you can use my share in the hub adcs://web-dev.airdcpp.net:1511 for listing the exact steps starting from opening of the filelist as it most likely depends on the share structure and the location of the files

**Comment by maksis** [comment] 2024-11-15 16:33
Closing due to no instructions for reproducing

**Closed by maksis** 2024-11-15 16:33 UTC
Labels: bug, can't reproduce
